Repository NullTraining/project-team1, pull requests merged in 2018-02, with the labels that each got.

#126 Add quality control tools
  composer.json
  composer.lock
  symfony.lock
Labels: ready to merge

#121 Issue #120 [Infra] - Run DataFixtures on CircleCI
  tests/Repository/PostRepositoryTest.php
Labels: infrastructure, ready to merge, tests

#133 Add logout button
  templates/partials/navbar.html.twig
Labels: bug, ready to merge

#135 CategoryRepository: Remove commented out code
  src/Repository/CategoryRepository.php
Labels: ready to merge

#141 Fix return type
  src/Entity/Post.php
Labels: ready to merge

#139 Issue 131
  config/routes.yaml
  templates/bundles/FOSUserBundle/Registration/confirmed.html.twig
  templates/bundles/FOSUserBundle/Registration/register.html.twig
  templates/partials/navbar.html.twig
Labels: ready to merge

#152 Add link to production on top of README file
  README.md
Labels: ready to merge

#155 Issuse #145 - Add missing entity property to db mapping
  src/Entity/Post.php
  src/Entity/PostComment.php
  src/Migrations/Version20180224124429.php
Labels: ready to merge

#146 Remove unused .gitignore files
  src/Controller/.gitignore
  src/DataFixtures/.gitignore
  src/DataFixtures/ORM/.gitignore
  src/Entity/.gitignore
  src/Migrations/.gitignore
  src/Repository/.gitignore
Labels: ready to merge

#153 Issue 140 admin bundle
  composer.lock
  config/bundles.php
  config/packages/easy_admin.yaml
  config/routes/easy_admin.yaml
  symfony.lock
Labels: ready to merge
